import NivoBar from './nivo-bar';
import NivoCalendar from './nivo-calendar';
import NivoHeatmap from './nivo-heatmap';
import NivoLine from './nivo-line';
import NivoPie from './nivo-pie';
import NivoStream from './nivo-stream';
import NivoTreemap from './nivo-treemap';
import NivoBubble from './nivo-bubble';
import UDSparklines from './sparklines';
import UDChart from './ud-chart';
import UdMonitor from './monitor';

UniversalDashboard.register("nivo-bar", NivoBar);
UniversalDashboard.register("nivo-calendar", NivoCalendar);
UniversalDashboard.register("nivo-heatmap", NivoHeatmap);
UniversalDashboard.register("nivo-line", NivoLine);
UniversalDashboard.register("nivo-pie", NivoPie);
UniversalDashboard.register("nivo-stream", NivoStream);
UniversalDashboard.register("nivo-treemap", NivoTreemap);
UniversalDashboard.register("nivo-bubble", NivoBubble);
UniversalDashboard.register("sparklines", UDSparklines);
UniversalDashboard.register("ud-chartjs", UDChart);
UniversalDashboard.register("chartjs-monitor", UdMonitor);